### ISSUE TITLE
[Major] New Version of EventEmitter 3 Breaks the Library

### ISSUE THREAD

**Issue by BonsaiDen** [nodejitsu/node-http-proxy#814] opened 2015-04-28 09:12 UTC
The latest version of `EventEmitter3` has removed the aliases on the exported Object:

https://github.com/primus/eventemitter3/commit/43211e9a9050887530421e8e2d8b9e1aa2506cc4

This of course breaks `http-proxy`'s require:

```
    EE3       = require('eventemitter3').EventEmitter,
```

```
Possibly unhandled TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (/home/ivo/dev/foo/node_modules/substrat/node_modules/http-proxy/lib/http-proxy/index.js:107:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ivo/dev/foo/node_modules/substrat/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:460:26)
```

Would be great if we could get semvers in `http-proxy`'s package.json to prevent future breakage due to major version changes in the required modules.

**Comment by 3rd-Eden** [comment] 2015-04-28 09:31
@BonsaiDen that happens in **old** and **out of date** versions of the http-proxy. Update to the latest version and it will work as intended. 

Duplicate of #810

**Closed by 3rd-Eden** 2015-04-28 09:31 UTC
